# Generated by Django 2.2.24 on 2021-09-14 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
        ('clase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='escuela.Escuela'),
        ),
    ]
