# Generated by Django 2.2.24 on 2021-09-14 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clase', '0001_initial'),
        ('escuela', '0001_initial'),
        ('student', '0002_class'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.AddField(
            model_name='student',
            name='clase',
            field=models.ManyToManyField(related_name='clase', to='clase.Clase'),
        ),
        migrations.AddField(
            model_name='student',
            name='escuela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='escuela.Escuela'),
        ),
    ]
